language: python
env:
  FLASK_CONFIG='testing'
  DATABASE_URL="postgresql://postgres:deepdot123@localhost/test_db"
  SECRET_KEY="mysupersupersecretkey"
  EMAIL="hcbullss@gmail.com"
  PASSWORD="hc_bullss"
python:
  - "3.6.5"
services:
  -postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before-script:
  - psql -c 'create database test_db;' -U postgres
script:
  - nosetests --exe -v --with-coverage --cover-package=app
  - coveralls
after_success:
 - coveralls
notifications:
  slack:
    on_success: never
    on_failure: never
  email: false
